// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewBlog struct {
	Author  string `json:"author"`
	Content string `json:"content"`
}

type UpdateBlog struct {
	ID      int    `json:"id"`
	Author  string `json:"author"`
	Content string `json:"content"`
}
